grid_map_topic: /grid_map_navigation_map/grid_map
grid_map_visualizations:
  # - name: elevation_points
  #   type: point_cloud
  #   params:
  #    layer: elevation
  - name: occupancy_grid
    type: occupancy_grid
    params:
     layer: type
     data_min: 0.0
     data_max: 1.0
  - name: occupancy_grid2
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.0
     data_max: 1.0
